import en_core_web_sm
nlp = en_core_web_sm.load()

# 3. visualizing the dependency   查看地址：http://127.0.0.1:5000/
from spacy import displacy
# sentence = 'A sender must not send a request with multiple headers with the same name.'
# sentence = 'The "*" value MUST NOT be generated by a proxy server; it may only be generated by an origin server.'
# sentence = 'A sender MUST NOT generate multiple header felds with the same feld name in a message.'
sentence = 'A server MUST respond with a 400 status code to any HTTP/1.1 request message that lacks a Host header feld and to any request message that contains more than one Host header feld or a Host header feld with an invalid feld-value. '

sentence = 'A server MUST respond with a 400 status code to any HTTP/1.1 request message that lacks a Host header feld;' \
           'A server MUST respond with a 400 status code to any request message that contains more than one Host header feld' \
           'A server MUST respond with a 400 status code to any request message that  a Host header feld with an invalid feld-value. '

doc = nlp(sentence)

# replace entities and noun chuncks
spans = list(doc.ents) + list(doc.noun_chunks)
for span in spans:
    span.merge()

displacy.serve(doc, style='dep')   # 实体：ent   依存：dep
